// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyZQeFZgE_p_x1wB04zKMX_87XYHenWas',
    appId: '1:833749469320:web:8d6c474fc0975e9308b73d',
    messagingSenderId: '833749469320',
    projectId: 'laween-f7c2d',
    authDomain: 'laween-f7c2d.firebaseapp.com',
    storageBucket: 'laween-f7c2d.firebasestorage.app',
    measurementId: 'G-43Y76WGVLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJkCK7wt-ADYZCFBxJFDSqoD6G1U69PI',
    appId: '1:833749469320:android:39b8e6caf147b52108b73d',
    messagingSenderId: '833749469320',
    projectId: 'laween-f7c2d',
    storageBucket: 'laween-f7c2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9eKa83dyDd6z_-rDIfsE04UxgjRFBhdQ',
    appId: '1:833749469320:ios:07a7a2aa3adfaff008b73d',
    messagingSenderId: '833749469320',
    projectId: 'laween-f7c2d',
    storageBucket: 'laween-f7c2d.firebasestorage.app',
    iosBundleId: 'com.example.laween',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9eKa83dyDd6z_-rDIfsE04UxgjRFBhdQ',
    appId: '1:833749469320:ios:07a7a2aa3adfaff008b73d',
    messagingSenderId: '833749469320',
    projectId: 'laween-f7c2d',
    storageBucket: 'laween-f7c2d.firebasestorage.app',
    iosBundleId: 'com.example.laween',
  );
}
